[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"

[sources]
TransformVariables = {path = ".."}

[compat]
Documenter = "1"
